parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '5.7'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            lp_perl:
                url: '%env(DATABASE_LP_PERL_URL)%'
                driver: pdo_mysql
                server_version: '5.7'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            lp_perl:
                connection: lp_perl
                mappings:
                    LpPerlEntity:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/LpPerlEntity'
                        prefix: 'App\LpPerlEntity'
                        alias: LpPerlEntity


