easy_admin:
    site_name: 'Laparfumerie'
    entities:
        Urls:
            class: App\Entity\Urls
            list:
                fields: ['id', 'url', 'type', 'created']
        Users:
            class: App\Entity\Users
            list:
                fields: ['id', 'email', 'roles']

        Catalog:
            class: App\Entity\Catalog
            list:
                fields: ['id', 'name', 'visible']

        Items:
            class: App\Entity\ProductItem
            list:
                fields: ['id', 'name', 'visible']

        Product:
            class: App\Entity\Product
            list:
                fields: ['id', 'name', 'visible']
            form:
                fields:
                    - { type: 'tab' , label: 'General' }
                    - visible
                    - name
                    - created
                    - updated
                    - { type: 'tab', label: 'Categories' }
                    - catalogs
                    - { type: 'tab', label: 'Product Items' }
                    - productItems
        Order:
            class: App\Entity\Orders
            list:
                fields: ['id', 'name', 'visible']
        Delivery:
              class: App\Entity\Delivery
              list:
                  fields: ['id', 'name', 'visible']
        PaymentMethod:
            class: App\Entity\PaymentMethod
            list:
                fields: ['id', 'name']
    design:
        brand_color: 'black'
