easy_admin:
    site_name: 'Laparfumerie'
    entities:
        Urls:
            class: App\Entity\Urls
            list:
                fields: ['id', 'url', 'created']
        ProductUrl:
            class: App\Entity\ProductUrl
            list:
                fields: ['id', 'url', 'created']
            form:
                fields:
                    - url
        CatalogUrl:
            class: App\Entity\CatalogUrl
            list:
                fields: ['id', 'url', 'created']
        Users:
            class: App\Entity\Users
            list:
                fields: ['id', 'email', 'roles']
        Menu:
            class: App\Entity\Menu
            list:
                fields: ['id', 'name', 'title']
        MenuItem:
            class: App\Entity\MenuItem
            list:
                fields: ['id', 'title']
        Catalog:
            class: App\Entity\Catalog
            list:
                fields: ['id', 'name', 'visible']
            form:
              fields:
                  - { type: 'tab' , label: 'General' }
                  - visible
                  - name
                  - created
                  - updated
                  - { type: 'tab', label: 'Virtual Urls' }
                  - { property: 'catalogUrls', type: 'easyadmin_autocomplete' }

        Items:
            class: App\Entity\ProductItem
            list:
                fields:
                    - id
                    - name
                    - visible
            form:
                fields:
                    - name
                    - { property: 'imageFile', type: 'App\Form\Type\MultipleImage', type_options: { multiple: true, block_name: 'custom_title' } }

        Product:
            class: App\Entity\Product
            list:
                fields: ['id', 'name', 'visible']
            form:
                fields:
                    - { type: 'tab' , label: 'General' }
                    - visible
                    - name
                    - created
                    - updated
                    - { type: 'tab', label: 'Categories' }
                    - catalogs
                    - { type: 'tab', label: 'Product Items' }
                    - productItems
                    - { type: 'tab', label: 'Virtual Urls' }
                    - { property: 'productUrls', type: 'easyadmin_autocomplete' }
        Order:
            class: App\Entity\Orders
            list:
                fields: ['id', 'name', 'visible']
        Delivery:
              class: App\Entity\Delivery
              list:
                  fields: ['id', 'name', 'visible']
        PaymentMethod:
            class: App\Entity\PaymentMethod
            list:
                fields: ['id', 'name']
        ImportProduct:
            class: App\Entity\ImportProduct

    design:
        brand_color: 'black'
        form_theme:
            - '@EasyAdmin/form/bootstrap_3_horizontal_layout.html.twig'
            - 'admin/form/images.html.twig'
        menu:
          - label: 'Urls'
            children: ['ProductUrl', 'CatalogUrl']
          - Users
          - Catalog
          - Items
          - Product
          - Order
          - Delivery
          - PaymentMethod
          - ImportProduct
          - label: 'Menu'
            children: ['Menu', 'MenuItem']
