easy_admin:
    site_name: 'Laparfumerie'
    entities:
        Tags:
            class: App\Entity\Tags
            form:
                fields:
                    - guid
        Urls:
            class: App\Entity\Urls
            list:
                fields: ['id', 'url', 'created']
        ProductUrl:
            class: App\Entity\ProductUrl
            list:
                fields: ['id', 'url', 'created']
            form:
                fields:
                    - url
        CatalogUrl:
            class: App\Entity\CatalogUrl
            list:
                fields: ['id', 'url', 'created']
        Users:
            class: App\Entity\Users
            list:
                fields: ['id', 'email', 'roles']
        Menu:
            class: App\Entity\Menu
            list:
                fields: ['id', 'name', 'title']
        MenuItem:
            class: App\Entity\MenuItem
            list:
                fields: ['id', 'title']
        Catalog:
            class: App\Entity\Catalog
            list:
                fields: ['id', 'name', 'visible']
            form:
              fields:
                  - { type: 'tab' , label: 'General' }
                  - visible
                  - name
                  - created
                  - updated
                  - { type: 'tab', label: 'Virtual Urls' }
                  - { property: 'catalogUrls', type: 'easyadmin_autocomplete' }

        Items:
            class: App\Entity\ProductItem
            controller: App\Controller\Admin\ItemsController
            list:
                fields:
                    - id
                    - name
                    - visible
            form:
                fields:
                    - name
                    - price
                    - { property: 'imageFile', type: 'App\Form\Type\MultipleImage', type_options: { multiple: true, block_name: 'custom_title' } }

        Product:
            class: App\Entity\Product
            controller: App\Controller\Admin\ProductController
            list:
                fields: ['id', 'name', 'visible']
            form:
                fields:
                    - { type: 'tab' , label: 'General' }
                    - visible
                    - name
                    - created
                    - updated
                    - { type: 'tab', label: 'Categories' }
                    - { property: 'catalogs', type: 'easyadmin_autocomplete' }
                    - { type: 'tab', label: 'Product Items' }
                    - { property: 'productItems', type: 'easyadmin_autocomplete' }
                    - { type: 'tab', label: 'Virtual Urls' }
                    - { property: 'productUrls', type: 'easyadmin_autocomplete' }
                    - { type: 'tab', label: 'Tags' }
                    - { property: 'productTags', type_options: { block_name: 'products_tags' }}
        Order:
            class: App\Entity\Orders
            list:
                fields: ['id', 'name', 'visible']
        Delivery:
              class: App\Entity\Delivery
              list:
                  fields: ['id', 'name', 'visible']
        PaymentMethod:
            class: App\Entity\PaymentMethod
            list:
                fields: ['id', 'name']
        ImportProduct:
            class: App\Entity\ImportProduct
            controller: App\Controller\Admin\ImportProductController
        ProductTag:
            class: App\Entity\ProductTag
            controller: App\Controller\Admin\ProductTagController
            form:
              fields:
                - name
                - { property: 'type', type: 'choice', type_options: {multiple: false, choices: {bool: 'bool', string: 'string', int: 'int', float: 'float', enum: 'enum'}} }
                - { property: 'visible', type: 'choice', type_options: {multiple: false, choices: {No: 'No', Yes: 'Yes'}}}
                - { property: 'productTagItems', type_options: { block_name: 'products_tags_items' }}

        Configuration:
            class: App\Entity\ProductTag
            controller: App\Controller\Admin\ConfigurationController
        Address:
            class: App\Entity\Address
            list:
                fields: ['id', 'city', 'street']
            form:
                fields:
                    - person
                    - user_id
                    - zip
                    - region_id
                    - city
                    - street
                    - house
                    - corp
                    - level
                    - flat
                    - code
                    - comment
                    - active
        Banner:
            class: App\Entity\Banner
            list:
                fields:
                    - id
                    - path
                    - link
            form:
                fields:
                    - { property: 'pathFile', type: 'App\Form\Type\MultipleImage', type_options: { multiple: true, block_name: 'custom_title' } }
                    - link
        Sale:
            class: App\Entity\Sale
            form:
                fields:
                    - start
                    - finish
                    - category
                    - discount
                    - enabled
                    - featured
                    - type
                    - prior
                    - { property: 'imagePath', type: 'App\Form\Type\MultipleImage', type_options: { multiple: true, block_name: 'custom_image' } }
    design:
        brand_color: 'black'
        form_theme:
            - 'admin/form/bootstrap_3_layout.html.twig'
            - 'admin/form/bootstrap_3_horizontal_layout.html.twig'
            - 'admin/form/images.html.twig'
            - 'admin/form/tags.html.twig'
            - 'admin/form/products_tags_items.html.twig'
        menu:
          - label: 'Urls'
            children: ['ProductUrl', 'CatalogUrl']
          - label: 'Catalog'
            children: ['Catalog', 'Product', 'Items', 'ProductTag']
          - label: 'Order'
            children: ['Order', 'Delivery', 'PaymentMethod', 'ProductTag']
          - label: 'User'
            children: ['Users', 'Address']
          - ImportProduct
          - label: 'Menu'
            children: ['Menu', 'MenuItem']
          - Banner
          - Sale
          - Configuration
          - Tags
        assets:
            css:
                - '/bundles/lp/css/lp.css'
