overblog_graphql:
    definitions:
        show_debug_info: true # Debug info is disabled by default
        builders:
            args:
                -
                    alias: "Pager"
                    class: "App\\GraphQL\\Args\\Pager"
        schema:
            query: Query
        mappings:
            auto_discover: false
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
    security:
        handle_cors: true # Disable cors
