twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        basket: '@App\Service\Twig\Basket'
        tags: '@App\Service\Twig\Tags'
