version: '2'
services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
        - POSTGRES_DB=symfony
        - POSTGRES_USER=symfony
        - POSTGRES_PASSWORD=symfony
        - PGDATA=/var/lib/postgresql/data/db-files/
#        volumes:
#        - db-data:/var/lib/postgresql/data:rw
        ports:
        - "5432:5432"
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ${PWD}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
            - postgres
            - db_lp:mysql
            - memcached
    nginx:
        build: nginx
        ports:
            - '8081:80'
            - '1337:1337'
        links:
            - php
            - node
        volumes_from:
            - php
            - node
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    db_lp:
        image: mariadb:latest
        restart: on-failure
        ports:
          - "3310:3306"
        volumes:
          - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
          - ./db:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=lp
          - MYSQL_USER=root
    memcached:
        image: memcached:1.4
        ports:
          - "11212:11211"
    node:
        image: "node:lts"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - ./front:/home/node/app
        command: "sh node.sh"
        expose:
            - "3000"
