version: '2'
services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
        - POSTGRES_DB=symfony
        - POSTGRES_USER=symfony
        - POSTGRES_PASSWORD=symfony
        - PGDATA=/var/lib/postgresql/data/db-files/
#        volumes:
#        - db-data:/var/lib/postgresql/data:rw
        ports:
        - "5432:5432"
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ${PWD}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
            - postgres
    nginx:
        build: nginx
        ports:
            - '8081:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached