Addresses:
  type: object
  config:
    description: "User Addresses"
    fields:
      token:
        type: "String!"
        description: "Token"
      data:
          type: AddressConnection
          argsBuilder: PaginatoringBuilder