Addresses:
  type: object
  config:
    description: "User Addresses"
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\AddressField", [info, value, args])'
    fields:
      data:
          type: AddressConnection
          argsBuilder: PaginatoringBuilder