Addresses:
  type: object
  config:
    description: "User Addresses"
    fields:
      id:
        type: "Int!"
        description: "Product Id."
      token:
        type: "String"
        description: "Product Name"
      url:
        type: "String"
        description: "Product Url"