Address:
  type: object
  config:
    description: "User Address"
    fields:
      id:
        type: "Int!"
        description: "Product Id."
      name:
        type: "String"
        description: "Address Name"
      user_id_id:
        type: "Int"
        description: "User ID"
      person:
        type: "String"
        description: "Person Address Name"
      zip:
        type: "String"
        description: "Post Code"
      region_id:
        type: "String"
        description: "Region ID"
      city:
        type: "String"
        description: "City"
      street:
        type: "String"
        description: "Street"
      house:
        type: "String"
        description: "House"
      corp:
        type: "String"
        description: "Corp"
      level:
        type: "String"
        description: "Level"
      flat:
        type: "String"
        description: "Flat"
      code:
        type: "String"
        description: "Code"
      active:
        type: "String"
        description: "Active"

