Catalog:
  type: object
  config:
    description: "Catalog"
    fields:
      id:
        type: "Int!"
        description: "Catalog Id."
      name:
        type: "String"
        description: "Catalog Name"
      products:
        type: "[Product]"
        description: "Define catalog products"
        argsBuilder:
                  builder: "Pager"
                  config:
                      defaultLimit: 50
        args:
            limit:
                type: "Int!"
                defaultValue: 20
            offset:
                type: "Int!"
                defaultValue: 0