Catalog:
  type: object
  config:
    description: "Catalog"
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\CatalogResolver", [info, value, args])'
    fields:
      id:
        type: "Int!"
        description: "Catalog Id."
      name:
        type: "String"
        description: "Catalog Name"
      products:
        type: ProductConnection
        argsBuilder: PaginatoringBuilder
      count:
        type: "Int!"
        description: "Count of products"