Mutation:
  type: object
  config:
    fields:
      auth:
        type: AuthorizedUser!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\UserMutation::auth", [args])'
        args:
          input:
            type: UserInput!
      addBasket:
        type: Basket!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\BasketMutation::add", [args])'
        args:
          input:
            type: AddBasketInput!
      removeBasket:
        type: Basket!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\BasketMutation::remove", [args])'
        args:
          input:
            type: AddBasketInput!
      updateBasket:
        type: Basket!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\BasketMutation::update", [args])'
        args:
          input:
            type: UpdateBasketInput!
      order:
        type: Order!
        resolve: '@=mutation("App\\GraphQL\\Mutation\\OrderMutation::create", [args])'