OrderInput:
  type: input-object
  config:
    fields:
      pvz_id:
        type: "Int!"
        description: "Pvz ID"
      courier_id:
        type: "Int"
        description: "Courier ID"
      address_id:
        type: "Int"
        description: "User Address Id"