Product:
  type: object
  config:
    description: "Product"
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\ProductResolver", [info, value, args])'
    fields:
      id:
        type: "Int!"
        description: "Product Id."
      name:
        type: "String"
        description: "Product Name"
      url:
        type: "String"
        description: "Product Url"
#      items:
#        type: ItemConnection
#        argsBuilder: PaginatoringBuilder