ProductItem:
  type: object
  config:
    description: "Product Item"
    fields:
      id:
        type: "Int!"
        description: "Product Item Id."
      name:
        type: "String"
        description: "Product Item Name"
      price:
        type: "String"
        description: "Product Item Price"