Product:
  type: object
  config:
    description: "Product"
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\ProductFieldResolver", [info, value, args])'
    fields:
      id:
        type: "Int!"
        description: "Product Id."
      name:
        type: "String"
        description: "Product Name"
      url:
        type: "String"
        description: "Product Url"
      items:
        type: ItemConnection
        argsBuilder: PaginatoringBuilder
      tags:
        type: "[ProductFilters]"
        description: "Product Filter"
      other_fragrance:
        type: "[ProductMini]"
        description: "Product Mini"
ProductFilters:
  type: object
  config:
    description: "Product Filter Item"
    fields:
      name:
        type: "String"
        description: "Product Filter Name."
      value:
        type: "String"
        description: "Product Filter Value"