Query:
  type: object
  config:
    description: "Product Item ORM repository"
    fields:
      productitem:
        type: "ProductItem"
        args:
            id:
              description: "Resolves using the product item id."
              type: "Int"
        resolve: "@=resolver('ProductItem', [args])"
      user:
        type: "User"
        args:
            id:
              description: "Resolves using the user id."
              type: "Int"
        resolve: "@=resolver('User', [args])"
      product:
        type: "Product"
        args:
            id:
              description: "Resolves using the product ID."
              type: "Int"
            slug:
              description: "Resolves using the product slug."
              type: "String"
        resolve: "@=resolver('Product', [args])"
      catalog:
        type: "Catalog"
        args:
            id:
              description: "Resolves using the catalog ID."
              type: "Int"
            slug:
              description: "Resolves using the catalog slug."
              type: "String"
            products:
              description: 'Products'
              type: "String"
        resolve: "@=resolver('Catalog', [args])"
      addresses:
        type: "Addresses"
        args:
          token:
            description: "User Token"
            type: "String"
        resolve: "@=resolver('Address', [args])"
      basket:
        type: "Basket"
        resolve: "@=resolver('Basket', [args])"
      banner:
        type: "Banner"
        resolve: "@=resolver('Banner', [args])"