Query:
  type: object
  config:
    description: "Product Item ORM repository"
    fields:
      productitem:
        type: "ProductItem"
        args:
            id:
              description: "Resolves using the product item id."
              type: "Int"
        resolve: "@=resolver('ProductItem', [args])"