Query:
  type: object
  config:
    description: "Product Item ORM repository"
    fields:
      productitem:
        type: "ProductItem"
        args:
            id:
              description: "Resolves using the product item id."
              type: "Int"
        resolve: "@=resolver('ProductItem', [args])"
      user:
        type: "Users"
        args:
            id:
              description: "Resolves using the user id."
              type: "Int"
        resolve: "@=resolver('User', [args])"
      product:
        type: "Product"
        args:
            id:
              description: "Resolves using the product ID."
              type: "Int"
        resolve: "@=resolver('Product', [args])"