app_logout:
    path: /logout

cms:
    resource: "Lp/CmsBundle/Resources/config/routing.yaml"

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation

urls:
    resource: "Lp/UrlsBundle/Resources/config/routing.yaml"

