app_logout:
    path: /logout

cms:
    resource: "Lp/CmsBundle/Resources/config/routing.yaml"

basket:
    resource: "Lp/BasketBundle/Resources/config/routing.yaml"

profile:
    resource: "Lp/ProfileBundle/Resources/config/routing.yaml"

easy_admin_bundle:
    resource: 'App\Controller\AdminController'
    prefix: /admin
    type: annotation

urls:
    resource: "Lp/UrlsBundle/Resources/config/routing.yaml"





